### ISSUE TITLE
Add it to PyPi

### ISSUE THREAD

**Issue by geekpete** [philgyford/ffffound-export#2]
Thanks for writing this :)

**Comment by philgyford** [comment]
I'm glad it's useful!

I hesitated over adding it to PyPi seeing as the code is only going to be useful for a week or two and I always struggle to find useful, current info about how to do so :)

**Comment by geekpete** [comment]
Yeah fair enough.

Downloading ffffound.com isn't really going to save what it was, an awesome way to stumble from visual strangeness to ocular amazement all the while opening new tabs and forgetting to close old ones...
