### ISSUE TITLE
Can you send me a picture compression pack?

### ISSUE THREAD

**Issue by 8088** [philgyford/ffffound-export#3]
when i try to run  get :

fffound image downloader

Downloading all pictures from user 'philgyford'

Capturing page 1 ...

Reached the end of the list for philgyford, stopping.

//nothing downloaded...

**Comment by philgyford** [comment]
I think ffffound.com is having some problems - sometimes when I visit the site I see a Cloudflare message at the top saying the site is down but they're serving a version of it from their cache.

Running the script, sometimes it works, and sometimes it fails, receiving a "504 Server Error: Gateway Time-out for url" - I expect this is what happened when you tried it.

I've changed the script so it will now report these errors, so you know what's happening. I can only suggest that you keep trying as it sometimes seems to get through, although it might not succeed fetching all pages. Good luck!

**Comment by 8088** [comment]
Thanks, It's working.
